version: "3.9"
services:
  stl-receiver:
    build: .
    container_name: stl_receiver
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - ./configs:/app/configs
      - ./audio_output:/app/audio
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/Bucharest
    restart: unless-stopped
